# Generated by Django 5.1.7 on 2025-03-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='isbn',
        ),
    ]
