# Generated by Django 5.1.7 on 2025-06-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('-created',)},
        ),
    ]
